"""PDF report generation using ReportLab."""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
from pathlib import Path
from typing import Dict, Any
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from backend.config import REPORTS_DIR


def generate_pdf_report(dataset_name: str, profile: Dict, quality: Dict,
                         automl_result: Dict, output_filename: str = None) -> str:
    if not output_filename:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_filename = f"report_{dataset_name}_{ts}.pdf"
    output_path = str(REPORTS_DIR / output_filename)

    doc = SimpleDocTemplate(output_path, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("title", parent=styles["Title"], fontSize=20,
                                  textColor=colors.HexColor("#4F46E5"), alignment=TA_CENTER)
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=14,
                         textColor=colors.HexColor("#1E1B4B"))
    body = styles["BodyText"]
    story = []

    # Header
    story.append(Paragraph("AI Data Intelligence Platform", title_style))
    story.append(Paragraph(f"Automated ML Report — {dataset_name}", styles["Heading2"]))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#4F46E5")))
    story.append(Spacer(1, 0.5*cm))

    # Dataset Summary
    story.append(Paragraph("1. Dataset Summary", h1))
    shape = profile.get("shape", {})
    summary_data = [
        ["Metric", "Value"],
        ["Dataset Name", dataset_name],
        ["Total Rows", str(shape.get("rows", "N/A"))],
        ["Total Columns", str(shape.get("columns", "N/A"))],
        ["Memory Usage", f"{profile.get('memory_usage', 0)} MB"],
        ["Duplicate Rows", str(profile.get("duplicate_rows", 0))],
        ["Total Missing Values", str(profile.get("total_missing", 0))],
        ["Missing %", f"{profile.get('missing_percentage', 0)}%"],
    ]
    t = Table(summary_data, colWidths=[8*cm, 8*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F3FF")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))

    # Data Quality
    story.append(Paragraph("2. Data Quality", h1))
    q_score = quality.get("quality_score", 0)
    story.append(Paragraph(f"Quality Score: {q_score}/100", body))
    recs = quality.get("recommendations", [])
    if recs:
        story.append(Paragraph("Recommendations:", body))
        for r in recs[:8]:
            story.append(Paragraph(f"• {r}", body))
    story.append(Spacer(1, 0.5*cm))

    # AutoML Results
    story.append(Paragraph("3. AutoML Results", h1))
    story.append(Paragraph(f"Problem Type: {automl_result.get('problem_type', 'N/A').title()}", body))
    story.append(Paragraph(f"Best Model: {automl_result.get('best_model', 'N/A')}", body))
    story.append(Paragraph(f"Best Score: {automl_result.get('best_score', 0):.4f}", body))
    story.append(Spacer(1, 0.3*cm))

    results = automl_result.get("results", [])
    if results:
        table_data = [["Model", "Score", "Training Time"]]
        for r in results:
            if r.get("score") is not None:
                table_data.append([r["model_name"], f"{r['score']:.4f}", f"{r.get('training_time', 0):.2f}s"])
        t2 = Table(table_data, colWidths=[8*cm, 4*cm, 4*cm])
        t2.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F3FF")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t2)

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Paragraph("Generated by AI Data Intelligence Platform", 
                            ParagraphStyle("footer", parent=body, alignment=TA_CENTER, fontSize=8, textColor=colors.grey)))

    doc.build(story)
    return output_path
